output * bg $wallpaper fill

set $display1 DP-1
set $display2 DP-2

output $display1 {
    mode 2560x1440@279.961Hz
    position 0 0
}
output $display2 {
    mode 1920x1080@60.000Hz
    position 2560 0
    # disable
}

workspace 1 output $display1
exec swaymsg focus output $display1

# 60 seconds (60 * 1000)
seat "*" hide_cursor 60000

exec swayidle -w \
  timeout 480 'swaylock -f' \
  timeout 600 'systemctl suspend' \
  before-sleep 'swaylock -f'
