icons_format = "{icon}"

[theme]
theme = "native"

[icons]
icons = "material-nf"

[[block]]
block = "custom"
format = " $text "
command = "swaymsg -t get_tree | jq '.. | select(.type?) | select(.focused).inhibit_idle'"
interval = 1
[[block.click]]
button = "left"
cmd = "swaymsg inhibit_idle focus"
update = true
[[block.click]]
button = "right"
cmd = "swaymsg inhibit_idle none"
update = true

[[block]]
block = "net"
format = " $icon "

[[block]]
block = "sound"
step_width = 1
[[block.click]]
button = "left"
cmd = "pavucontrol"
[[block.click]]
button = "right"
cmd = "wpctl set-mute @DEFAULT_SINK@ toggle"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %m/%d %H:%M:%S') "
interval = 1
