icons_format = "{icon}"

[theme]
theme = "semi-native"
[theme.overrides]
good_fg = "#9ece6a"
warning_fg = "#e0af68"
critical_fg = "#f7768e"
info_fg = "#7aa2f7"

[icons]
icons = "awesome6"

[[block]]
block = "pacman"
signal = 5
interval = 600
format = " $icon $both "
format_singular = " $icon $both "
format_up_to_date = " $icon $both "
warning_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "paru -Qua"
[[block.click]]
button = "left"
update = true

[[block]]
block = "cpu"
format = " $icon $utilization "
interval = 1

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "disk_space"
path = "/"
format = " $path $available "
format_alt = " $path $percentage "
info_type = "available"
alert_unit = "GB"

[[block]]
block = "music"
format = " $icon { $prev $play $next $volume }"
player = "spotify"
[[block.click]]
button = "up"
cmd = "playerctl volume 0.01+"
[[block.click]]
button = "down"
cmd = "playerctl volume 0.01-"

[[block]]
block = "bluetooth"
mac = "30:53:C1:32:5F:3B"

[[block]]
block = "sound"
step_width = 1
[[block.click]]
button = "left"
cmd = "pavucontrol"
[[block.click]]
button = "right"
cmd = "pactl set-sink-mute @DEFAULT_SINK@ toggle"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %m/%d %H:%M:%S') "
interval = 1

[[block]]
block = "menu"
text = " \uf011 "
[[block.items]]
display = " sleep "
cmd = "systemctl suspend"
confirm_msg = " sleep?"
[[block.items]]
display = " poweroff "
cmd = "poweroff"
confirm_msg = " poweroff?"
[[block.items]]
display = " reboot "
cmd = "reboot"
confirm_msg = " reboot?"
