icons_format = "{icon}"

[theme]
theme = "native"
[theme.overrides]
# idle_fg = ""
good_fg = "#9ece6a"
warning_fg = "#e0af68"
critical_fg = "#f7768e"
info_fg = "#7aa2f7"

[icons]
icons = "awesome6"

[[block]]
block = "pacman"
signal = 1
aur_command = "paru -Qua"

[[block]]
block = "cpu"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "bluetooth"
mac = "30:53:C1:32:5F:3B"

[[block]]
block = "battery"

[[block]]
block = "backlight"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[[block.click]]
button = "right"
cmd = "amixer set Master toggle"
[[block.click]]
button = "up"
cmd = "amixer set Master 2%+"
[[block.click]]
button = "down"
cmd = "amixer set Master 2%-"

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%a %d/%m %I:%M %p') "

[[block]]
block = "menu"
text = " \uf011 "
[[block.items]]
display = " sleep "
cmd = "systemctl suspend"
confirm_msg = "sleep?"
[[block.items]]
display = " poweroff "
cmd = "poweroff"
confirm_msg = "poweroff?"
[[block.items]]
display = " reboot "
cmd = "reboot"
confirm_msg = "reboot?"
