icons_format = "{icon}"

[theme]
theme = "native"

[icons]
icons = "material-nf"
[icons.overrides]
backlight = ["\uf185"]

[[block]]
block = "custom"
format = " $text "
command = "swaymsg -t get_tree | jq '.. | select(.type?) | select(.focused).inhibit_idle'"
interval = 1
[[block.click]]
button = "left"
cmd = "swaymsg inhibit_idle focus"
update = true
[[block.click]]
button = "right"
cmd = "swaymsg inhibit_idle none"
update = true

[[block]]
block = "backlight"
device = "intel_backlight"
missing_format = ""
cycle = [20]

[[block]]
block = "battery"
device = "DisplayDevice"
driver = "upower"
format = " $icon $percentage "
charging_format = " $icon $percentage "
not_charging_format = " $icon $percentage "
missing_format = ""

[[block]]
block = "net"
format = " $icon "

[[block]]
block = "sound"
step_width = 2
[[block.click]]
button = "left"
cmd = "pavucontrol"
[[block.click]]
button = "right"
cmd = "wpctl set-mute @DEFAULT_SINK@ toggle"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %m/%d %H:%M:%S') "
interval = 1
