icons_format = "{icon}"

[theme]
theme = "native"
[theme.overrides]
idle_fg = "#e6e1cf"
info_fg = "#59c2ff"
good_fg = "#b8cc52"
warning_fg = "#ffb454"
critical_fg = "#f07178"

[icons]
icons = "awesome6"

[[block]]
block = "pacman"
signal = 5
interval = 600
error_interval = 300
format = " $icon $both "
format_singular = " $icon $both "
format_up_to_date = " $icon $both "
warning_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "paru -Qua"
error_format = "update query error"
[[block.click]]
button = "left"
update = true

[[block]]
block = "backlight"
device = "intel_backlight"
missing_format = ""
cycle = [20]

[[block]]
block = "battery"
device = "BAT0"
driver = "upower"
format = " $icon $percentage "
charging_format = " $icon $percentage $time "
not_charging_format = " $icon $percentage $time "
missing_format = ""

[[block]]
block = "music"
format = " $icon $volume "
player = "spotify"
error_format = ""
[[block.click]]
button = "left"
cmd = "playerctl play-pause"
[[block.click]]
button = "forward"
cmd = "playerctl next"
[[block.click]]
button = "backward"
cmd = "playerctl previous"
[[block.click]]
button = "up"
cmd = "playerctl volume 0.01+"
[[block.click]]
button = "down"
cmd = "playerctl volume 0.01-"

[[block]]
block = "bluetooth"
mac = "30:53:C1:32:5F:3B"

[[block]]
block = "sound"
step_width = 1
[[block.click]]
button = "left"
cmd = "pavucontrol"
[[block.click]]
button = "right"
cmd = "pactl set-sink-mute @DEFAULT_SINK@ toggle"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %m/%d %H:%M:%S') "
interval = 1

[[block]]
block = "menu"
text = " \uf011 "
[[block.items]]
display = " sleep "
cmd = "systemctl suspend"
confirm_msg = " sleep?"
[[block.items]]
display = " poweroff "
cmd = "poweroff"
confirm_msg = " poweroff?"
[[block.items]]
display = " reboot "
cmd = "reboot"
confirm_msg = " reboot?"
